### ISSUE TITLE
Running npInv on .bam file

### ISSUE THREAD

**Issue by simarilion** [haojingshao/npInv#10]
Like some previous users I'm also having an issue getting npInv to run (I guess this is to do with the MD:Z flag in the .bam file). I used Minimap2 to generate the read mappings like so:

`minimap2 --MD -t 16 -ax map-ont genome_input_file.fa nanopore_reads.fastq.gz >mapped_reads.sam`

I then converted the .sam file to a .bam file like so:

`samtools view --threads 16 -b -o mapped_reads.bam mapped_reads.sam`

... and I also sorted the .bam file:

`samtools sort -o mapped_reads_sorted.bam -T temp_folder --threads 16 mapped_reads.bam`

When I run npInv like so:

`java -jar /usr/local/bin/npInv/npInv1.27.jar --input mapped_reads_sorted.bam --output npInv_output.VCF`

I get this error:

#<INFO-2> Program starts at 2021/02/01 10:19:13
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NoClassDefFoundError: htsjdk/samtools/SamReaderFactory
	at inversion.Main.main(Main.java:120)
	... 5 more
Caused by: java.lang.ClassNotFoundException: htsjdk.samtools.SamReaderFactory
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:436)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 6 more

Any help would be gratefully received!

**Comment by simarilion** [comment]
For good measure I see the MD:Z flags in the .bam file:

`samtools view mapped_reads_sorted.bam | head -n 5`

Gives:

c6f6ee33-a375-46cd-a6c5-707c43429858	etc. etc. etc. ....**MD:Z**:9^C8C1T1T0T10.....

**Comment by glaudelrio** [comment]
I am facing the same issue... any news on how to solve it?

**Comment by glaudelrio** [comment]
This is how the first lines of my alignment look like:

`A00564:131:HLCYHDSXX:2:1104:22679:16282	97	chr1	1	1	2S111M37S	chrUn_scaffold_10261	42	0	ATCCCTTGTCCCCAGTCCCTCTCCAGCTCTCCTGGAGCCCCTTTGGGCTCTGGAAGGGGCTCTCAGCTCTCCCTGGATCCTTCTGGACATTCCCAGCATTCCCAGCCTGGCTCCAGAGCAGCTCCAGCCCTTGGAGCATCTCCGTGGCCT	688998:97888899788898988997989889978978889::9777989978997777989899798988899788889:89978798:88899798:8889978997798899897997988997889::89:8:99:9928:8899	SA:Z:chr1,803371,+,81S69M,1,0;	XA:Z:chr1,-7963,150M,13;chr2,-599670,72S78M,1;	MC:Z:48S43M59S	MD:Z:44A1A14G2G46	PG:Z:MarkDuplicates	RG:Z:4	NM:i:4	AS:i:91	XS:i:89
A00564:131:HLCYHDSXX:2:1150:30083:11475	163	chr1	1	43	25S125M	=	276	425	CATTCCCTGTGTCCTGTCCCTCCATCCCTTGTCCCCAGTCCCTCTCCAGCTCTCCTGGAGCCCCTCTGGGTTCTGGAAGGGGCTCTGAGGTCTCCCTGGATCCTTCTGGACATTCCCAGCATTCCCAGTCTGGCTCCCTGGGCAAACTAT	698;9789979788997888988988889:97888899788898988997989889978978889899777:89978997777989989778788899788889:89978798:88899798:8889978::88:999::888:::8:98	MC:Z:150M	MD:Z:40T3A0C0A56C7T13	PG:Z:MarkDuplicates	RG:Z:4	NM:i:6AS:i:95	XS:i:92
A00564:131:HLCYHDSXX:2:1159:19271:30765	99	chr1	1	0	45S105M	=	7	156	TCCCAACATCCCACCTGACACATTCCCTGTGTCCTGTCCCTCCATCCCTTGTCCCCAGTCCCTCTCCAGCTCTCCTGGAGCCCCTTTGGACACTGGAAGGGGCTCTGAGGTCTCCCTGGATCCTTCTGGACATTCCCAGCATTCCCAGTC	6889:879888897899879798:8889979788997888988988889:97888899788898988997989889978978889::9787979978997777989989778988899788889:89978799;999::8:9;999::88	SA:Z:chrUn_scaffold_5198,9879,-,66S84M,0,1;	XA:Z:chr1,-357689,44S106M,1;chrUn_scaffold_5602,+5526,99M51S,0;chr8,-4999974,23S107M20S,3;chr27,-1929762,30S100M20S,2;	MC:Z:150M	MD:Z:103C1	PG:Z:MarkDuplicates	RG:Z:4	NM:i:1AS:i:103	XS:i:101
A00564:131:HLCYHDSXX:2:1407:20853:35352	161	chr1	1	0	18S111M21S	=	803371	803447	TGTGTCCTGTCCCTCCATCCCTTGTCCCCAGTCCCTCTCCAGCTCTCCTGGAGCCCCTTTGGACACTGGAAGGGGCTCTCAGCTCTCCCTGGATCCTTCTGGACATTCCCAGCATTCCCAGCCTGGCTCCAGAGCAGCTCCAGCCCTTGG	697:878997888988988889:97888899788898988997989889978978889::9787979978997777989899798988899788889:89978798:88899798:88899789977988::9:8::8:99::899:;:7	SA:Z:chr4,3106695,-,35M115S,0,0;	XA:Z:chr1,-7979,150M,10;chr8,-4999974,50S100M,3;chr5,+72726989,99M51S,3;chr1,-357680,62S88M,1;	MC:Z:28S77M45S	MD:Z:61G2G46	PG:Z:MarkDuplicates	RG:Z:4	NM:i:2	AS:i:101	XS:i:100
A00564:131:HLCYHDSXX:2:1524:7925:17159	161	chr1	1	55	111M39S	=	803371	803447	CCCTTGTCCCCAGTCCCTCTCCAGCTCTCCTGGAGCCCCTTTGGACACTGGAAGGGGCTCTCAGCTCTCCCTGGATCCTTCTGGACATTCCCAGCATTCCCAGCCTGGCTCCAGAGCAGCTCCAGCCCTTGGAGCATCTCCGTGGCCTCC	688:;87888899788898988997989889978978889::9787979978897777989899798988899788889:89978798:88899798:8889978997798869897997988997889::89:8:99:9928:889:98	SA:Z:chr1,803371,+,79S71M,55,0;	MC:Z:29S77M44S	MD:Z:61G2G46	PG:Z:MarkDuplicates	RG:Z:4	NM:i:2	AS:i:101	XS:i:77`

**Comment by haojingshao** [comment]
I am so sorry for the late reply.
I add the missing libraries and export the jar again. Please try the new version npInv1.28.

**Comment by glaudelrio** [comment]
Hi, thank you very much! I am back to npInv, and I got another error now:

![image](https://user-images.githubusercontent.com/10550113/166616105-a9138bdf-fb74-490a-8e26-72269c3e3616.png)

any idea on what could be going on?
Thank you and sorry for any inconvenience
