### ISSUE TITLE
java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by wdecoster** [haojingshao/npInv#2]
Hi,

I was running npInv on some PromethION WGS data of NA19240 and came across the error pasted below. The bam is from a minimap2 alignment to GRCh38.
```
#<INFO-2> Program starts at 2018/07/16 09:49:58
#<INFO-3> Running chromosome chr1 at2018/07/16 09:49:59
#<INFO-4> Progressing chromosome chr1 at 2018/07/16 09:49:59
#<INFO-3> Running chromosome chr2 at2018/07/16 11:16:31
#<INFO-4> Progressing chromosome chr2 at 2018/07/16 11:16:31
#<INFO-3> Running chromosome chr3 at2018/07/16 11:44:45
#<INFO-4> Progressing chromosome chr3 at 2018/07/16 11:44:45
#<INFO-3> Running chromosome chr4 at2018/07/16 12:02:30
#<INFO-4> Progressing chromosome chr4 at 2018/07/16 12:02:30
#<INFO-3> Running chromosome chr5 at2018/07/16 12:26:19
#<INFO-4> Progressing chromosome chr5 at 2018/07/16 12:26:19
#<INFO-3> Running chromosome chr6 at2018/07/16 12:54:54
#<INFO-4> Progressing chromosome chr6 at 2018/07/16 12:54:54
#<INFO-3> Running chromosome chr7 at2018/07/16 13:12:20
#<INFO-4> Progressing chromosome chr7 at 2018/07/16 13:12:20
#<INFO-3> Running chromosome chr8 at2018/07/16 13:30:43
#<INFO-4> Progressing chromosome chr8 at 2018/07/16 13:30:43
#<INFO-3> Running chromosome chr9 at2018/07/16 13:44:43
#<INFO-4> Progressing chromosome chr9 at 2018/07/16 13:44:43
#<INFO-3> Running chromosome chr10 at2018/07/16 13:59:48
#<INFO-4> Progressing chromosome chr10 at 2018/07/16 13:59:48
#<INFO-3> Running chromosome chr11 at2018/07/16 14:26:35
#<INFO-4> Progressing chromosome chr11 at 2018/07/16 14:26:35
#<INFO-3> Running chromosome chr12 at2018/07/16 14:39:44
#<INFO-4> Progressing chromosome chr12 at 2018/07/16 14:39:44
#<INFO-3> Running chromosome chr13 at2018/07/16 14:54:37
#<INFO-4> Progressing chromosome chr13 at 2018/07/16 14:54:37
#<INFO-3> Running chromosome chr14 at2018/07/16 15:05:31
#<INFO-4> Progressing chromosome chr14 at 2018/07/16 15:05:31
#<INFO-3> Running chromosome chr15 at2018/07/16 15:14:52
#<INFO-4> Progressing chromosome chr15 at 2018/07/16 15:14:52
#<INFO-3> Running chromosome chr16 at2018/07/16 15:26:23
#<INFO-4> Progressing chromosome chr16 at 2018/07/16 15:26:23
#<INFO-3> Running chromosome chr17 at2018/07/16 15:58:44
#<INFO-4> Progressing chromosome chr17 at 2018/07/16 15:58:44
#<INFO-3> Running chromosome chr18 at2018/07/16 16:09:05
#<INFO-4> Progressing chromosome chr18 at 2018/07/16 16:09:05
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.IllegalArgumentException: Comparison method violates its general contract!
        at java.util.ComparableTimSort.mergeHi(ComparableTimSort.java:866)
        at java.util.ComparableTimSort.mergeAt(ComparableTimSort.java:483)
        at java.util.ComparableTimSort.mergeCollapse(ComparableTimSort.java:404)
        at java.util.ComparableTimSort.sort(ComparableTimSort.java:213)
        at java.util.Arrays.sort(Arrays.java:1312)
        at java.util.Arrays.sort(Arrays.java:1506)
        at java.util.ArrayList.sort(ArrayList.java:1454)
        at java.util.Collections.sort(Collections.java:141)
        at inversion.Main.runBam(Main.java:838)
        at inversion.Main.runChr(Main.java:219)
        at inversion.Main.main(Main.java:128)
        ... 5 more
```

What do you suggest?

Cheers,
Wouter

**Comment by haojingshao** [comment]
HI Wouter,
Sorry for replying late.
The program get some inversions, but fails to sort it somehow. Would you please provide the parameter to run it and also a simple example input?

Best regards,
Haojing

**Comment by wdecoster** [comment]
Hi Haojing,

It probably doesn't surprise you that I no longer have the files which I used when trying your tool.  
I am now rerunning the same command. I use a minimap2 aligned bam from NA19240 PromethION sequencing as input and a vcf as output, no other parameters specified.

The tool completed without issues on a smaller dataset of just chr22, I am now again running the full 60x covered genome and will let you know how it goes.

Wouter

**Comment by haojingshao** [comment]
Hello Wouter,

npInv should work for Minimap2. To run it "parallelly", you can split the genome into chromosome and run it separately. Good luck.

Haojing

**Comment by wdecoster** [comment]
Hi Haojing,

I could reproduce the issue on chromosome 18 separately and you can find the bam file [here](https://mega.nz/#!iB1yVYia!Y1WFEe-NnnDLicvodTx32hg1jTSW3HhBIhYDXVvqvkA)
Please let me know when you have downloaded it, then I can remove it again.

Cheers,
Wouter

**Comment by haojingshao** [comment]
Hi Wouter,
I downloaded your file and reproduced the bug. It is an overflow problem. npInv1.2 should work without error if your reference doesn't contain chromosome like "chr17_XX_random". I fixed it and got a result from your chr18. Please try npInv1.21.jar.

cheers,
Haojing

**Comment by wdecoster** [comment]
Everything seems okay now, thanks!
