### ISSUE TITLE
Still java.lang.reflect.InvocationTargetException with latest version 2.5

### ISSUE THREAD

**Issue by JhinAir** [haojingshao/npInv#8]
Hi,

I still got the java.lang.reflect.InvocationTargetException error as shown in the last issues.
The command is as follow:
java -jar npInv1.25.jar --input test.bam --output test.vcf --minAln 100 --min 100 --max 1000000 --window 200 --threshold 1
>>>>>>>
#<INFO-1> Arguments= --input test.bam --output test.vcf --minAln 100 --min 100 --max 1000000 --window 200 --threshold 1
#<INFO-2> Program starts at 2019/07/26 17:48:03
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NoClassDefFoundError: htsjdk/samtools/SamReaderFactory
        at inversion.Main.main(Main.java:120)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: htsjdk.samtools.SamReaderFactory
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 6 more
>>>>>>>

It reported this even I tried the default par or changed the ref chr name or reads name. Could you please help with this? The test bam is attached. Thanks.

Best~
Jing

[test.zip](https://github.com/haojingshao/npInv/files/3436501/test.zip)

**Comment by haojingshao** [comment]
HI Jing,
Sorry for the late reply. This is because your reads are very long. The old htsjdk library does not support it. I update the library and compile it to npInv1.26.jar. It works for your test date although no inversion is detected.

Best regards,
Haojing

**Comment by JhinAir** [comment]
Hi, Haojing,

Thanks for the help. But it's weird I still get the same error.
java -jar npInv1.26.jar --input test.bam --output test.vcf --minAln 100 --min 100 --max 1000000 --window 200 --threshold 1
<<<<<<<<<<<
#<INFO-1> Arguments= --input test.bam --output test.vcf --minAln 100 --min 100 --max 1000000 --window 200 --threshold 1
#<INFO-2> Program starts at 2019/07/31 09:42:42
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:564)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NoClassDefFoundError: htsjdk/samtools/SamReaderFactory
        at inversion.Main.main(Main.java:120)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: htsjdk.samtools.SamReaderFactory
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 6 more
<<<<<<<<<<<
It may also depend on some environment libraries?

Best~
Jing

**Comment by haojingshao** [comment]
I try. Every version of the jars work for me. I can't repeat your error.
What is your java version and system version?  Can you send the full error messages? Do you index your bam?

**Comment by JhinAir** [comment]
It's because of Java version. Java1.8 can work. Thanks.
