### ISSUE TITLE
npInv-1.26 not working

### ISSUE THREAD

**Issue by MarioWassmer** [haojingshao/npInv#9]
I tried to run npInv-1.26 with the command java -jar npInv1.26.jar --input input.bam --output result.vcf
and get the following error:

Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NoClassDefFoundError: htsjdk/samtools/SamReaderFactory
        at inversion.Main.main(Main.java:120)
        ... 5 more
Caused by: java.lang.ClassNotFoundException: htsjdk.samtools.SamReaderFactory
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 6 more

seems like htsjdk isn't inlcuded in the jar. On conda, only version 1.24 is available. This version leads to a completely malformed header.

Regards,

Mario

**Comment by haojingshao** [comment]
Hi Mario,

I am so sorry for the late reply. I was on holiday.
I update the htsjdk to 2.21.1. The new jar (1.27) is working and the old jar (1.26) is working too. Thus I suspect the problem is from the aligner. Do your bam files contain field "MD:Z"? The expected aligner are bwa, minimap2 and ngmlr. I update this information in the readme. 

Regards,
Haojing

**Comment by haojingshao** [comment]
Hello Mario,
I add the missing libraries and export the jar again. Please try the new version npInv1.28.
best wishes,
Haojing
